#!/usr/bin/env node
// Bundle RunViewer into cli/viewer.mjs — a JS module that default-exports the
// viewer's IIFE bundle AS A STRING. `slink open` imports that string and
// serves it, so the viewer travels inside the CLI with no separate asset
// file: it inlines when the CLI is esbuild-bundled for npm and embeds when
// compiled to a Bun binary. (react + lucide + inline styles only.)
import { fileURLToPath } from "node:url";
import path from "node:path";
import esbuild from "esbuild";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const result = await esbuild.build({
  entryPoints: [path.join(root, "packages", "viewer", "viewer-entry.tsx")],
  bundle: true,
  minify: true,
  write: false,
  format: "iife",
  jsx: "automatic",
  alias: { "@": root },
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "warning",
});

const js = result.outputFiles[0].text;
const { writeFile } = await import("node:fs/promises");
await writeFile(
  path.join(root, "cli", "viewer.mjs"),
  `// Generated by scripts/build-viewer.mjs — do not edit.\nexport default ${JSON.stringify(js)};\n`,
);
console.log(`built cli/viewer.mjs (${(js.length / 1024).toFixed(0)} KB viewer)`);
